version: "3"

#volumes:
#  postgres_data:
#    driver: local

services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx-keycloak
    ports:
      - 8081:80
    volumes:
#      - ./myapp:/usr/share/nginx/html
      - type: bind
        source: /home/david/docker/test/nginx/html
        target: /usr/share/nginx/html
      - type: bind
        source: /home/david/docker/test/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: /home/david/docker/test/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15.2-alpine3.17
    container_name: postgres-keycloak
    volumes:
      - type: bind
        source: /home/david/docker/test/postgres
        target: /var/lib/psql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 15432:5432

  keycloak:
    image: keycloak/keycloak:21.0
    container_name: keycloak
    environment:
      db-url: postgres:15432
      db: postgres
      db-username: keycloak
      db-password: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      features: token-exchange
    command: 
      - start-dev
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: /home/david/docker/test/keycloak
        target: /opt/keycloak/data/import 
    depends_on:
      - postgres
      - smtp4dev

  smtp4dev:
    image: rnwood/smtp4dev:linux-amd64-3.2.0-ci20221023104
    container_name: smtp-keycloak
    ports:
      - 13000:80
