version: "3"

networks:
  gitea:
    external: true

services:
  server:
    image: gitea/gitea:1.18-linux-amd64
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - type: bind
        source: /home/david/docker/test/gitea
        target: /data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone:ro
      - type: bind
        source: /etc/localtime
        target: /etc/localtime:ro
    ports:
      - "3001:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:alpine3.17
    container_name: postgres-gitea
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - type: bind
        source: /home/david/docker/test/postgres
        target: /var/lib/psql/data